# numpy
1. Numpy 설치
  Numpy는 pip를 통해 쉽게 설치가 가능하다. $는 설치하기 위한 명령어
  ``` 
  $pip install numpy
  ```

In [8]:
# !pip install numpy
import numpy as np


# Numpy 배열 생성
numpy에서 가장 중요한 객체는 ndarray로 다차원 배열을 생성하고 관리할 수 있다.

1. list를 배열로 변환

In [14]:
arr = [1,2,3,4,5]
print(arr)
type(arr)

[1, 2, 3, 4, 5]


list

In [13]:
ndarry = np.array(arr)
print(ndarry)
type(ndarry)

[1 2 3 4 5]


numpy.ndarray

2. 다차원 배열

In [11]:
arr_2d = np.array([[1, 2, 3], [3, 4, 5]])
print(arr_2d)
type(arr_2d)

[[1 2 3]
 [3 4 5]]


numpy.ndarray

3.ndarray배열의 속성
- 배열의 중요한 속성들을 확인하는 것은 배열을 구조를 파악하는데 필수적이다.<br>
  배열의 구조에 따라 데이터를 조작하는 방식이 달라지기 때문이다.

In [19]:
print(ndarry.shape) # 배열의 차원을 확인 : 1차원 배열이 5개
print(arr_2d.shape) # : 2차원 배열 2개 1차원 배열 3개

print(ndarry.dtype) # 데이터의 타입을 확인
print(arr_2d.dtype)

print(ndarry.ndim) # 배열의 차원 수 확인
print(arr_2d.ndim)

(5,)
(2, 3)
int64
int64
1
2


4. 배열 초기화
- numpy는 배열을 초기화하는 여러 방법을 제공한다.

In [23]:
arr_2d = np.zeros((3,3)) # 3 * 3 배열을 생성한다.
print(arr_2d)
print("---------")

arr_2d = np.ones((2,2)) # 2 * 2 배열을 생성하고 값을 1로 채움
print(arr_2d)
print("---------")

arr_2d = np.full((3,3), 7) # 3*3 배열을 생성하고 값을 원하는 값(여기선 7)으로 채움
print(arr_2d)
print("---------")

arr_2d = np.random.random((2,2)) # 2*2 배열을 생성하고 값을 랜덤하게 채움
print(arr_2d)
print("---------")


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1.]
 [1. 1.]]
---------
[[7 7 7]
 [7 7 7]
 [7 7 7]]
---------
[[0.08856084 0.82803221]
 [0.72397447 0.23847465]]
---------


# 배열 연산 및 슬라이싱
- numpy는 백터화된 연산을 ㅅ지원하여 배열 간의 연산을 매우 효율적으로 처리한다.

In [31]:
arr1 = [1,2,3]
arr2 = [4,5,6]
result = arr1 + arr2
print(result)

[1, 2, 3, 4, 5, 6]


In [32]:
# list 간 덧셈
# 백터 연산을 통해 두 배열의 같은 인덱스 위치에 값을 더한다.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)


[5 7 9]


In [33]:
# 배열 간 행렬 곱
result = arr1 * arr2
print(result)

[ 4 10 18]


In [34]:
# 배열 간 행렬 곱
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

# 연산 과정
# 1*5 + 2*7 = 5, 14
# 1*6 + 2*8 = 6, 16
# 3*5 + 4*7 = 15, 28
# 3*6 + 4*8 = 18, 32


result = np.dot(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


# 배열으 슬라이싱 및 인덱싱

In [35]:
# 1차원 배열 슬라이싱
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # 1번 인덱스에서 4미만 인덱스 까지

[2 3 4]


In [39]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr_2d)
print("---------")
print(arr_2d[:2, 1:])

# 결과
# [[:2 - 0부터 2까지  -> 행을 지시
# 1:]] - 1부터 마지막까지 -> 열을 지시

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------
[[2 3]
 [5 6]]


# 배열의 형태 변경

In [40]:
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape((2,3)) # 2 * 3 배열로 변경
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [41]:
# 조건별 값 선택
arr = np.array([1,2,3,4,5])
condition = arr>3
list = [False, False, False, True, True]

filtered_arr = arr[condition]
print(filtered_arr)

index = []
for x in arr :
  result = x >3
  index.append(result)

[4 5]


In [42]:
# 고차원 배열
# numpy는 1차원 배열뿐만 아니라 3차원, 4차원 이상의 고차원 배열도 쉽게 다룰 수 있다.
arr_3d = np.random.random((3,3,3)) #3*3*3 차원 배열 생성
print(arr_3d)

[[[0.5093209  0.53471741 0.6337266 ]
  [0.36323527 0.85911067 0.31027524]
  [0.95099059 0.07003003 0.98830614]]

 [[0.2873234  0.53888002 0.89664314]
  [0.84987535 0.72740354 0.34963012]
  [0.18072053 0.98978258 0.05998437]]

 [[0.36178355 0.37583236 0.84883101]
  [0.89022388 0.98839206 0.44318256]
  [0.13452113 0.70405311 0.03776825]]]


In [46]:
# 브로드캐스팅
# 브로드캐스팅은 서로 다른 크기의 배열 간의 연산을 가능하게 하는 강력한 기능이다.
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([4,5,6])
print(arr1)
print(arr2)

[[1]
 [2]
 [3]]
[4 5 6]


In [48]:
# 브로드캐스팅
# 브로드캐스팅은 서로 다른 크기의 배열 간의 연산을 가능하게 하는 강력한 기능이다.
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)

# 연산과정
# 1+4, 1+5, 1+6
# 2+4, 2+5, 2+6
# 3+4, 3+5, 3+6

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [49]:
# 고급 인덱싱 및 슬라이싱
# numpyt는 불리언 배열과 정수 배열을 사용하여 복잡한 인덱싱을 지원한다.
arr = np.array([10,20,30,40])
bool_arr = np.array([True, False, True, False])
filtered = arr[bool_arr]
print(filtered)


[10 30]


# 배열 합치기 및 나누기
- 배열을 수평 또는 수직으로 합치거나 나누는 방법이다.

In [54]:
# 배열 합치기
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

# axis는 (0,1)의 값을 가질 수 있다.
# 0 = 행을 기준으로 합치는 조건
# 1 = 열을 기준으로 합치는 조건

concatenated0 = np.concatenate((arr1,arr2),axis=0)
concatenated1 = np.concatenate((arr1,arr2),axis=1)
print(concatenated0)
print("-------")
print(concatenated1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------
[[1 2 5 6]
 [3 4 7 8]]


In [56]:
# 배열 나누기
arr = np.array([[1,2,3], [4,5,6]])

# split 자르는 메서드

split_arr = np.split(arr, 2, axis=0)
print(split_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


# 고급 : Numpy 성능 최적화

In [58]:
# 벡터화 연산과 for 루프의 비교
arr = np.random.random(1000000) # 100만개의 난수 생성

%timeit np.sum(arr)

# for 루프의 연산
def slow_sum(arr):
  total = 0
  for i in arr:
    total += i
  return total

%timeit slow_sum(arr)

1.15 ms ± 15.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
124 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
# 메모리 관리 및 배열
# numpy는 메모리를 활용해 효율적인 배열 복사를 지원하며, 명시적으로 복사하지 않으면 같은 메모리 주소를 공유한다.

arr = np.array([1,2,3])
arr_copy = arr.copy()
print(arr_copy)



list_copy = arr
  
print(list_copy)


[1 2 3]
[1 2 3]


In [ ]:
# 고급 수학 함수
# NumPy는 선형 대수, 푸리에 변환, 통계 함수 등 고급 수학 함수들을 제공한다.

# 선형 대수
# 역행렬
# 정사각 행렬 𝐴A에 대해, 그 행렬과 곱했을 때 단위 행렬(identity matrix)을 만들어내는 행렬이다. 쉽게 말하면, 역행렬은 행렬을 "원래 상태로 돌려놓는" 역할을 하는 행렬이다.
arr = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(arr)  # 역행렬 구하기
print("역행렬 : ")
print(inverse)
print()

# 표준편차
mean = np.mean(arr)
std_dev = np.std(arr)
print("통계 함수 : ")
print(std_dev)